### ISSUE TITLE
FYI - JBCameraView

### ISSUE THREAD

**Issue by billinghamj** [verylargebox/VLBCameraView#10]
I just recently forked and made a modified version of VLBCameraView. It now holds copyright notices for both VLB and Cuvva (my company).

I believe I've set up all the licence & copyright stuff correctly, but just as a courtesy, I wanted to point you to it in case you need me to change anything.

It's just here: https://github.com/billinghamj/JBCameraView

Let me know if there are any problems in terms of following your original licence properly.

Thanks

**Comment by qnoid** [comment]
Looks good to me @billinghamj.
Glad to be of service and all the best with Cuvva.
